DROP TABLE IF EXISTS `t_employment`;
CREATE TABLE `t_employment` (
  `id` int(50) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `stu_id` varchar(50) DEFAULT '' COMMENT '学号',
  `name` varchar(100) DEFAULT NULL COMMENT '姓名',
  `gender` varchar(20) DEFAULT NULL COMMENT '性别',
  `phone` varchar(255) DEFAULT '' COMMENT '电话',
  `education` varchar(255) DEFAULT '' COMMENT '学历',
  `college` varchar(255) DEFAULT '' COMMENT '学院',
  `major` varchar(255) DEFAULT '' COMMENT '专业',
  `class_num` varchar(255) DEFAULT NULL COMMENT '班级号',
  `enter_date` varchar(255) DEFAULT '' COMMENT '入学日期',
  `graduate_date` varchar(255) DEFAULT '' COMMENT '毕业日期',
  `identify_id` varchar(255) DEFAULT '' COMMENT '身份证号',
  `home_address` varchar(255) DEFAULT NULL,
  `take_table` varchar(255) DEFAULT '' COMMENT '是否领表0,未领取，1领取',
  `employment_status` varchar(255) DEFAULT NULL COMMENT '就业状态，证明，自谋',
  `sign_status` varchar(255) DEFAULT NULL COMMENT '签约状态：参军、出国、合同、三方、升本、升硕、村官、社区、西部',
  `poor_student` varchar(255) DEFAULT NULL COMMENT '困难生',
  `employ_pattern` varchar(255) DEFAULT '' COMMENT '就业模式：证明、自谋',
  `sign_pattern` varchar(255) DEFAULT '' COMMENT '签约方式：参军、出国、合同、三方、升本、升硕、村官、社区、西部',
  `sign_company` varchar(255) DEFAULT '' COMMENT '签约公司',
  `tutor` varchar(255) DEFAULT NULL COMMENT '导师',
  `comment` varchar(500) DEFAULT NULL,
  `sign_company_address` varchar(255) DEFAULT '' COMMENT '签约公司地址',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=844 DEFAULT CHARSET=utf8;
